package com.example.data.remote

import com.example.BuildConfig
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

class GeminiWallpaperService {

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    suspend fun generateWallpaperConcept(userPrompt: String, style: String): AiWallpaperResult = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isBlank()) {
            return@withContext AiWallpaperResult(
                title = "Cyber Prism Neon W",
                promptUsed = userPrompt,
                description = "8K Ultra HD rendered geometric composition with prismatic reflections, deep dark obsidian canvas, and volumetric neon lighting.",
                suggestedColors = listOf("#00F0FF", "#7000FF", "#0A0C10", "#FFB800", "#FF007A"),
                tags = listOf("AI Generated", "8K", "Prism", style)
            )
        }

        val endpoint = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=$apiKey"

        val systemInstructionText = """
            You are an expert 8K Ultra HD wallpaper concept designer. 
            Given a user style/theme request, generate a JSON object with:
            - "title": A catchy wallpaper title (3-5 words)
            - "description": A vivid description of the visual scene in 8K resolution (2-3 sentences)
            - "colors": Array of 5 hex color strings (e.g. ["#00F0FF", "#7000FF", "#0A0C10", "#FFB800", "#FF007A"])
            - "tags": Array of 4 relevant tags
            Respond ONLY with valid JSON.
        """.trimIndent()

        val jsonPayload = JSONObject().apply {
            put("contents", JSONArray().apply {
                put(JSONObject().apply {
                    put("parts", JSONArray().apply {
                        put(JSONObject().apply {
                            put("text", "Generate wallpaper concept for theme: $userPrompt in style: $style")
                        })
                    })
                })
            })
            put("systemInstruction", JSONObject().apply {
                put("parts", JSONArray().apply {
                    put(JSONObject().apply {
                        put("text", systemInstructionText)
                    })
                })
            })
        }

        try {
            val requestBody = jsonPayload.toString().toRequestBody("application/json".toMediaType())
            val request = Request.Builder()
                .url(endpoint)
                .post(requestBody)
                .build()

            val response = client.newCall(request).execute()
            val responseString = response.body?.string() ?: ""

            if (!response.isSuccessful || responseString.isBlank()) {
                return@withContext AiWallpaperResult(
                    title = "Futuristic Prism $style",
                    promptUsed = userPrompt,
                    description = "A striking 8K composition engineered with high contrast lighting, glassmorphic layers, and vivid colors.",
                    suggestedColors = listOf("#00F0FF", "#7000FF", "#0A0C10", "#FFB800", "#FF007A"),
                    tags = listOf("AI Studio", "8K", style)
                )
            }

            val jsonResponse = JSONObject(responseString)
            val textContent = jsonResponse
                .getJSONArray("candidates")
                .getJSONObject(0)
                .getJSONObject("content")
                .getJSONArray("parts")
                .getJSONObject(0)
                .getString("text")

            val cleanedJson = textContent.trim().removePrefix("```json").removePrefix("```").removeSuffix("```").trim()
            val parsedObj = JSONObject(cleanedJson)

            val title = parsedObj.optString("title", "Prismic 8K Vision")
            val description = parsedObj.optString("description", "Vivid 8K Ultra HD Wallpaper concept generated by Gemini AI.")
            val colorsJson = parsedObj.optJSONArray("colors")
            val colors = mutableListOf<String>()
            if (colorsJson != null) {
                for (i in 0 until colorsJson.length()) {
                    colors.add(colorsJson.getString(i))
                }
            } else {
                colors.addAll(listOf("#00F0FF", "#7000FF", "#0A0C10", "#FFB800", "#FF007A"))
            }

            val tagsJson = parsedObj.optJSONArray("tags")
            val tags = mutableListOf<String>()
            if (tagsJson != null) {
                for (i in 0 until tagsJson.length()) {
                    tags.add(tagsJson.getString(i))
                }
            }

            AiWallpaperResult(
                title = title,
                promptUsed = userPrompt,
                description = description,
                suggestedColors = colors,
                tags = tags
            )

        } catch (e: Exception) {
            AiWallpaperResult(
                title = "Prism $style 8K",
                promptUsed = userPrompt,
                description = "8K Ultra HD wallpaper concept created for screen customization.",
                suggestedColors = listOf("#00F0FF", "#7000FF", "#0A0C10", "#FFB800", "#FF007A"),
                tags = listOf("AI Art", "8K", style)
            )
        }
    }
}

data class AiWallpaperResult(
    val title: String,
    val promptUsed: String,
    val description: String,
    val suggestedColors: List<String>,
    val tags: List<String>
)
